-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT '2ae946bb2647d60b' HASH '09148b0a0f2c2cd07b9c6b0b3709dafc8ab97dac2b725c8ffb676372e20e7071' ADMIN;         
CREATE SEQUENCE "PUBLIC"."ACTIVITY_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."APPLICATION_REQUEST_SEQ" START WITH 1 INCREMENT BY 50;              
CREATE SEQUENCE "PUBLIC"."FEEDBACK_SEQ" START WITH 1 INCREMENT BY 50;         
CREATE SEQUENCE "PUBLIC"."PARTICIPANT_GROUP_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;               
CREATE SEQUENCE "PUBLIC"."PARTICIPANT_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;     
CREATE MEMORY TABLE "PUBLIC"."ACTIVITY"(
    "GROUP_ID" BIGINT,
    "ID" BIGINT NOT NULL,
    "ACTIVITY_NAME" CHARACTER VARYING(255),
    "CREATED_BY" CHARACTER VARYING(255),
    "DATE" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "ACTIVITY_STATUS" ENUM('Done', 'InProgress')
);       
ALTER TABLE "PUBLIC"."ACTIVITY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");     
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.ACTIVITY;               
INSERT INTO "PUBLIC"."ACTIVITY" VALUES
(5, 1, 'Christmas Carol Singing', '', '2023-12-18', 'An evening of singing Christmas carols with the group.', 'InProgress'),
(5, 2, 'Decorating the Christmas Tree', '', '2023-12-05', 'Decorating the Christmas tree together as a group.', 'Done'),
(3, 3, 'Christmas Cookie Bake-off', '', '2023-12-10', 'A fun baking competition for Christmas cookies.', 'InProgress'),
(4, 4, 'Santa Hat Crafting', '', '2023-12-12', 'Get creative and make your own Santa hats!', 'InProgress'),
(5, 5, 'Secret Santa Gift Exchange', '', '2023-12-20', 'Exchange gifts anonymously with group members.', 'InProgress'),
(3, 6, 'Christmas Dinner Feast', '', '2023-12-25', 'A Christmas-themed group dinner with festive dishes.', 'InProgress'),
(1, 7, 'Writing Letters to Santa', '', '2023-12-01', 'A group activity to write letters to Santa.', 'Done'),
(2, 8, 'Gingerbread House Decorating', '', '2023-12-08', 'Decorate gingerbread houses together as a group.', 'InProgress'),
(3, 9, 'Christmas Movie Night', '', '2023-12-15', 'Watch Christmas classics like Home Alone and Elf.', 'InProgress'),
(4, 10, 'Ugly Christmas Sweater Contest', '', '2023-12-14', 'Show off your best worst sweater for Christmas!', 'Done'),
(5, 11, 'Holiday Card Making Workshop', '', '2023-12-09', 'Make custom holiday cards for friends and family.', 'InProgress'),
(3, 12, 'Christmas Lights Tour', '', '2023-12-19', 'Visit the best decorated areas in town.', 'InProgress'),
(1, 13, 'Christmas Karaoke', '', '2023-12-13', 'Sing your favorite Christmas tunes together.', 'Done'),
(2, 14, 'Winter Wonderland Hike', '', '2023-12-16', 'Explore a snowy trail in the spirit of the season.', 'InProgress'),
(3, 15, 'Wrapping Gifts for Charities', '', '2023-12-22', 'Wrap gifts to donate to those in need this holiday season.', 'InProgress'),
(4, 16, 'Christmas Ornament Crafting', '', '2023-12-07', 'Create custom ornaments to decorate the tree.', 'InProgress'),
(5, 17, 'Hot Cocoa Social', '', '2023-12-17', 'Warm up with hot cocoa and good conversation.', 'InProgress');          
CREATE MEMORY TABLE "PUBLIC"."APPLICATION_REQUEST"(
    "IS_APPLIED" BOOLEAN NOT NULL,
    "ID" BIGINT NOT NULL,
    "USER_ID" BIGINT
);  
ALTER TABLE "PUBLIC"."APPLICATION_REQUEST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A1" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.APPLICATION_REQUEST;     
CREATE MEMORY TABLE "PUBLIC"."CHATMESSAGE"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "PARTICIPANT_ID" BIGINT NOT NULL,
    "TIMESTAMP" TIMESTAMP(6) NOT NULL,
    "CONTENT" CHARACTER VARYING(255) NOT NULL
);       
ALTER TABLE "PUBLIC"."CHATMESSAGE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_CB" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CHATMESSAGE;             
CREATE MEMORY TABLE "PUBLIC"."FEEDBACK"(
    "ACTIVITY_ID" BIGINT,
    "ID" BIGINT NOT NULL,
    "PARTICIPANT_ID" BIGINT,
    "COMMENT" CHARACTER VARYING(255),
    "IS_LIKED" ENUM('Dislike', 'Like', 'None')
);       
ALTER TABLE "PUBLIC"."FEEDBACK" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FEEDBACK;
CREATE MEMORY TABLE "PUBLIC"."PARTICIPANT"(
    "ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT,
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "USERNAME" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."PARTICIPANT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_AE1" PRIMARY KEY("ID");
-- 28 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPANT;            
INSERT INTO "PUBLIC"."PARTICIPANT" VALUES
(1, 1, 'johndoe@example.com', 'John_Doe'),
(2, 1, 'janesmith@example.com', 'Jane_Smith'),
(3, 1, 'michaelbrown@example.com', 'Michael_Brown'),
(4, 1, 'sarahjones@example.com', 'Sarah_Jones'),
(5, 1, 'davidjohnson@example.com', 'David_Johnson'),
(6, 1, 'emilydavis@example.com', 'Emily_Davis'),
(7, 1, 'chrismiller@example.com', 'Chris_Miller'),
(8, 1, 'amandawilson@example.com', 'Amanda_Wilson'),
(9, 1, 'jamesmoore@example.com', 'James_Moore'),
(10, 1, 'jessicataylor@example.com', 'Jessica_Taylor'),
(11, 1, 'williamanderson@example.com', 'William_Anderson'),
(12, 1, 'oliviathomas@example.com', 'Olivia_Thomas'),
(13, 1, 'ethanjackson@example.com', 'Ethan_Jackson'),
(14, 1, 'sophiawhite@example.com', 'Sophia_White'),
(15, 1, 'liamharris@example.com', 'Liam_Harris'),
(16, 2, 'benjaminmartin@example.com', 'Benjamin_Martin'),
(17, 2, 'emmagarcia@example.com', 'Emma_Garcia'),
(18, 2, 'danielrodriguez@example.com', 'Daniel_Rodriguez'),
(19, 2, 'gracelewis@example.com', 'Grace_Lewis'),
(20, 2, 'samuelwalker@example.com', 'Samuel_Walker'),
(21, 3, 'miahall@example.com', 'Mia_Hall'),
(22, 3, 'alexanderallen@example.com', 'Alexander_Allen'),
(23, 3, 'avayoung@example.com', 'Ava_Young'),
(24, 3, 'isabellaking@example.com', 'Isabella_King'),
(25, 3, 'noahwright@example.com', 'Noah_Wright'),
(26, 2, 'progitest6@gmail.com', 'progitest'),
(27, 1, 'antewert1@gmail.com', 'antisa'),
(28, 1, 'antemrkonjic0908@gmail.com', 'antem');
CREATE MEMORY TABLE "PUBLIC"."PARTICIPANT_GROUP"(
    "ID" BIGINT NOT NULL,
    "PRESIDENT" BIGINT,
    "NAME" CHARACTER VARYING(20) NOT NULL
);          
ALTER TABLE "PUBLIC"."PARTICIPANT_GROUP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_80" PRIMARY KEY("ID");           
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPANT_GROUP;       
INSERT INTO "PUBLIC"."PARTICIPANT_GROUP" VALUES
(1, 16, 'Group1'),
(2, 17, 'Group2'),
(3, 18, 'Group3'),
(4, 19, 'Group4'),
(5, 26, 'Group5');           
CREATE MEMORY TABLE "PUBLIC"."PARTICIPANT_GROUP_MEMBERS"(
    "MEMBERS_ID" BIGINT NOT NULL,
    "PARTICIPANT_GROUP_ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."PARTICIPANT_GROUP_MEMBERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F1" PRIMARY KEY("MEMBERS_ID", "PARTICIPANT_GROUP_ID");   
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.PARTICIPANT_GROUP_MEMBERS;              
INSERT INTO "PUBLIC"."PARTICIPANT_GROUP_MEMBERS" VALUES
(16, 1),
(1, 1),
(2, 1),
(27, 1),
(17, 2),
(3, 2),
(4, 2),
(18, 3),
(5, 3),
(6, 3),
(19, 4),
(7, 4),
(8, 4),
(26, 5),
(9, 5),
(10, 5),
(28, 5);      
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ROLE_ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255)
);   
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_26" PRIMARY KEY("ROLE_ID");   
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;    
INSERT INTO "PUBLIC"."ROLE" VALUES
(1, 'Participant'),
(2, 'President'),
(3, 'Admin');     
ALTER TABLE "PUBLIC"."APPLICATION_REQUEST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" UNIQUE("USER_ID");          
ALTER TABLE "PUBLIC"."PARTICIPANT_GROUP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" UNIQUE("NAME");               
ALTER TABLE "PUBLIC"."PARTICIPANT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_AE" UNIQUE("EMAIL");   
ALTER TABLE "PUBLIC"."PARTICIPANT_GROUP_MEMBERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" UNIQUE("MEMBERS_ID"); 
ALTER TABLE "PUBLIC"."PARTICIPANT_GROUP" ADD CONSTRAINT "PUBLIC"."FK1WUJ5A90DM96JPTOCTW4I93JB" FOREIGN KEY("PRESIDENT") REFERENCES "PUBLIC"."PARTICIPANT"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."FEEDBACK" ADD CONSTRAINT "PUBLIC"."FKM1CKVH3WPERFQ36BXVC7XQHA6" FOREIGN KEY("ACTIVITY_ID") REFERENCES "PUBLIC"."ACTIVITY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."APPLICATION_REQUEST" ADD CONSTRAINT "PUBLIC"."FKTCQR7M3W4KS5NH4O8SNALTTMC" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."PARTICIPANT"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."FEEDBACK" ADD CONSTRAINT "PUBLIC"."FKBIN0LB767H7FYICL9YNV8U4V3" FOREIGN KEY("PARTICIPANT_ID") REFERENCES "PUBLIC"."PARTICIPANT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."CHATMESSAGE" ADD CONSTRAINT "PUBLIC"."FK7HB6JHEDS4RS27AVTLG2QNVG1" FOREIGN KEY("PARTICIPANT_ID") REFERENCES "PUBLIC"."PARTICIPANT"("ID") NOCHECK;       
ALTER TABLE "PUBLIC"."ACTIVITY" ADD CONSTRAINT "PUBLIC"."FKK59O8EXVCXR6CY2824JG3I8HM" FOREIGN KEY("GROUP_ID") REFERENCES "PUBLIC"."PARTICIPANT_GROUP"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."PARTICIPANT" ADD CONSTRAINT "PUBLIC"."FKT72BQFUR0RRRUE1XA7MQ60WGI" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ROLE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PARTICIPANT_GROUP_MEMBERS" ADD CONSTRAINT "PUBLIC"."FKHTTGHYWKL6XPVXWE8B7I275KF" FOREIGN KEY("PARTICIPANT_GROUP_ID") REFERENCES "PUBLIC"."PARTICIPANT_GROUP"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."PARTICIPANT_GROUP_MEMBERS" ADD CONSTRAINT "PUBLIC"."FKM55SKHGG10DCO42R083G09AE4" FOREIGN KEY("MEMBERS_ID") REFERENCES "PUBLIC"."PARTICIPANT"("ID") NOCHECK;             
